const mongoose = require('mongoose');

// Define the Customer schema
const CustomerSchema = new mongoose.Schema({
    CreatDate: { type: String, default: "" },
    SalesOrg: { type: String, default: "" },
    Customer: { type: String, default: "" },
    CompanyCode: { type: String, default: "" },
    AcctGrp: { type: String, default: "" },
    DistChan: { type: String, default: "" },
    DistChanDesc: { type: String, default: "" },
    Div: { type: String, default: "" },
    SalesOff: { type: String, default: "" },
    SalesOffDesc: { type: String, default: "" },
    SalesGrp: { type: String, default: "" },
    SalesGrpDesc: { type: String, default: "" },
    BranchCode: { type: String, default: "" },
    BranchCodeDesc: { type: String, default: "" },
    SearchTerm: { type: String, default: "" },
    NAME1: { type: String, default: "" },
    NAME2: { type: String, default: "" },
    NAME3: { type: String, default: "" },
    NAME4: { type: String, default: "" },
    CustGrpDesc: { type: String, default: "" },
    ShippingCondDesc: { type: String, default: "" },
    BranchCode1: { type: String, default: "" },
    BranchName1: { type: String, default: "" },
    BankKey1: { type: String, default: "" },
    BankAccountNumber1: { type: String, default: "" },
    AcctHolder1: { type: String, default: "" },
    BankName1: { type: String, default: "" },
    ReferenceDetail1: { type: String, default: "" },
    BankKey2: { type: String, default: "" },
    BankAccountNumber2: { type: String, default: "" },
    AcctHolder2: { type: String, default: "" },
    BankName2: { type: String, default: "" },
    ReferenceDetail2: { type: String, default: "" },

    BankKey3: { type: String, default: "" },
    BankAccountNumber3: { type: String, default: "" },
    AcctHolder3: { type: String, default: "" },
    BankName3: { type: String, default: "" },
    ReferenceDetail3: { type: String, default: "" },

    BankKey4: { type: String, default: "" },
    BankAccountNumber4: { type: String, default: "" },
    AcctHolder4: { type: String, default: "" },
    BankName4: { type: String, default: "" },
    ReferenceDetail4: { type: String, default: "" },

    BankKey5: { type: String, default: "" },
    BankAccountNumber5: { type: String, default: "" },
    AcctHolder5: { type: String, default: "" },
    BankName5: { type: String, default: "" },
    ReferenceDetail5: { type: String, default: "" },

    BankKey6: { type: String, default: "" },
    BankAccountNumber6: { type: String, default: "" },
    AcctHolder6: { type: String, default: "" },
    BankName6: { type: String, default: "" },
    ReferenceDetail6: { type: String, default: "" },

    BankKey7: { type: String, default: "" },
    BankAccountNumber7: { type: String, default: "" },
    AcctHolder7: { type: String, default: "" },
    BankName7: { type: String, default: "" },
    ReferenceDetail7: { type: String, default: "" },

    BankKey8: { type: String, default: "" },
    BankAccountNumber8: { type: String, default: "" },
    AcctHolder8: { type: String, default: "" },
    BankName8: { type: String, default: "" },
    ReferenceDetail8: { type: String, default: "" },

    BankKey9: { type: String, default: "" },
    BankAccountNumber9: { type: String, default: "" },
    AcctHolder9: { type: String, default: "" },
    BankName9: { type: String, default: "" },
    ReferenceDetail9: { type: String, default: "" },

    BankKey10: { type: String, default: "" },
    BankAccountNumber10: { type: String, default: "" },
    AcctHolder10: { type: String, default: "" },
    BankName10: { type: String, default: "" },
    ReferenceDetail10: { type: String, default: "" },

    CustomerGroup1: { type: String, default: "" },
    CustomerGroup2: { type: String, default: "" },
    CustomerGroup3: { type: String, default: "" },
    CustomerGroup4: { type: String, default: "" },
    CustomerGroup5: { type: String, default: "" },
    SalesCustomerGroup1: { type: String, default: "" },
    SalesCustomerGroup2: { type: String, default: "" },
    SalesCustomerGroup3: { type: String, default: "" },
    SalesCustomerGroup4: { type: String, default: "" },
    SalesCustomerGroup5: { type: String, default: "" },
    AC: { type: String, default: "" },
    ACName: { type: String, default: "" },
    SH: { type: String, default: "" },
    SHName: { type: String, default: "" },
    Z1: { type: String, default: "" },
    Z1Name: { type: String, default: "" },
    Z4: { type: String, default: "" },
    Z4Name: { type: String, default: "" },
    SP: { type: String, default: "" },
    SPName: { type: String, default: "" },
    BP: { type: String, default: "" },
    BPName: { type: String, default: "" },
    PY: { type: String, default: "" },
    PYName: { type: String, default: "" },
    TS: { type: String, default: "" },
    TSName: { type: String, default: "" },
    Z3: { type: String, default: "" },
    Z3Name: { type: String, default: "" },
    Z7: { type: String, default: "" },
    Z7Name: { type: String, default: "" },
    BC: { type: String, default: "" },
    BCName: { type: String, default: "" },
    SE: { type: String, default: "" },
    SEName: { type: String, default: "" },
    AccountingClerk: { type: String, default: "" },
    ADRNR: { type: String, default: "" },
    Street: { type: String, default: "" },
    Street4: { type: String, default: "" },
    Street5: { type: String, default: "" },
    CityCode: { type: String, default: "" },
    CityName: { type: String, default: "" },
    DistrictCode: { type: String, default: "" },
    DistrictName: { type: String, default: "" },
    Region1: { type: String, default: "" }, // Assuming there are two Region fields, change accordingly
    Region2: { type: String, default: "" },
    PostalCode: { type: String, default: "" },
    Tel: { type: String, default: "" },
    TransportationZone: { type: String, default: "" },
    TeamA: { type: String, default: "" },
    TeamAName: { type: String, default: "" },
    TeamB: { type: String, default: "" },
    TeamBName: { type: String, default: "" },
    SalesDistrict: { type: String, default: "" },
    SalesDistrictDesc: { type: String, default: "" },
    PrevMastRecNo: { type: String, default: "" },
    Buying: { type: String, default: "" },
    CustGrp: { type: String, default: "" },
    PriceList: { type: String, default: "" },
    PaymentTerm: { type: String, default: "" },
    Text1: { type: String, default: "" },
    Text2: { type: String, default: "" },
    AROfficer: { type: String, default: "" },
    AccMemo: { type: String, default: "" },
    Currency1: { type: String, default: "" },
    CrLimit: { type: String, default: "" },
    Currency2: { type: String, default: "" },
    CreateBy: { type: String, default: "" },
    OrderBlk: { type: String, default: "" },
    DelivBlk: { type: String, default: "" },
    BillingBlk: { type: String, default: "" },
    SalesBlk: { type: String, default: "" },
    PostingBlk: { type: String, default: "" },
    ShippingCond: { type: String, default: "" },
    CustClass: { type: String, default: "" },
    TaxNo1: { type: String, default: "" },
    TaxNo2: { type: String, default: "" },
    TaxNo3: { type: String, default: "" },
    TaxNo4: { type: String, default: "" },
    MobilePhone1: { type: String, default: "" },
    MobilePhone2: { type: String, default: "" },
    MobilePhone3: { type: String, default: "" },
    MobilePhone4: { type: String, default: "" },
    MobilePhone5: { type: String, default: "" },
    Fax1: { type: String, default: "" },
    EMail1: { type: String, default: "" },
    Notes1: { type: String, default: "" },
    EMail2: { type: String, default: "" },
    Notes2: { type: String, default: "" },
    EMail3: { type: String, default: "" },
    Notes3: { type: String, default: "" },
    EMail4: { type: String, default: "" },
    Notes4: { type: String, default: "" },
    EMail5: { type: String, default: "" },
    Notes5: { type: String, default: "" },
    Comment: { type: String, default: "" },
    W53: { type: String, default: "" },
    IndustryKey: { type: String, default: "" },
    ReconAccount: { type: String, default: "" },
    CashMgmtGroup: { type: String, default: "" },
    CustCondGrp1: { type: String, default: "" },
    CustCondGrp2: { type: String, default: "" },
    CustCondGrp3: { type: String, default: "" },
    CustCondGrp4: { type: String, default: "" },
    CustCondGrp5: { type: String, default: "" },
    TaxClassification: { type: String, default: "" },
    PriceGroup: { type: String, default: "" },
    CustomerGrp1: { type: String, default: "" },
    CustomerGrp2: { type: String, default: "" },
    CustomerGrp3: { type: String, default: "" },
    CustomerGrp4: { type: String, default: "" },
    CustomerGrp5: { type: String, default: "" },
    BillingType: { type: String, default: "" }, // Assuming ประเภทการวางบิล is a Billing Type
    IndustryCode1: { type: String, default: "" },
    PhoneNoExt: { type: String, default: "" },
    BPExtNo: { type: String, default: "" },
    IndustryCode1Desc: { type: String, default: "" },
    VehicleControlForm: { type: String, default: "" },
});

CustomerSchema.index({ TaxNo3: 'text' , 'Customer': 'text'});

// Create the Customer model based on the schema
const Customer = mongoose.model('Customer', CustomerSchema);

// Export the Customer model
module.exports = Customer;
