openapi: 3.0.0
info:
  version: 1.0.0
  title: User API
  description: API documentation for user management
tags:
  - name: Users
    description: User management
paths:
  /users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      summary: Get a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
    put:
      summary: Update a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/me:
    get:
      summary: Get current user
      tags:
        - Users
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/getSelection:
    get:
      summary: Get selection user
      tags:
        - Users
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/active/{id}:
    put:
      summary: Activate a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User activated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/inactive/{id}:
    put:
      summary: Activate a user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User activated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/searchNameOrEmployeeId:
    post:
      summary: Search user by name or employeeId
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                searchText:
                  type: string
              example:
                searchText: John Doe
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/approvedList:
    get:
      summary: Get all approved users
      tags:
        - Users
      parameters:
        - name: searchText
          in: query
          description: Text to search for in users' information
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/rejectedList:
    get:
      summary: Get all rejected users
      tags:
        - Users
      parameters:
        - name: searchText
          in: query
          description: Text to search for in users' information
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        employeeId:
          type: string
        password:
          type: string
        name:
          type: string
        userType:
          type: string
        role:
          type: string
        level:
          type: string
        email:
          type: string
        distChannel:
          type: string
        companyCode:
          type: string
        salesGroup:
          type: string
        salesDistrict:
          type: string
        isActive:
          type: Boolean
        isRequestActive:
          type: Boolean
        isApprove:
          type: Boolean
        isReject:
          type: Boolean
        doaTag:
          type: string
      example:
        username: johndoe
        employeeId: '123456'
        password: password
        name: John Doe
        userType: Sale
        role: Office
        level: S1
        email: johndoe@example.com
        distChannel: '10'
        companyCode: '1100'
        salesGroup: '111'
        salesDistrict: '11101'
        isActive: false
        isRequestActive: false
        isApprove: false
        isReject: false
        doaTag: 'CEO'
    UserHierachy:
      type: object
      properties:
        salesDistrict:
          type: string
        requesterEmployeeId:
          type: string
        approverEmployeeId:
          type: string
        approverEmployeeIdSecond:
          type: string
        reviewerEmployeeId:
          type: string
        acknowledgeEmployeeId:
          type: string
      example:
        salesDistrict: '111001'
        requesterEmployeeId: '111'
        approverEmployeeId: '333'
        approverEmployeeIdSecond: '666'
        reviewerEmployeeId: '999'
        acknowledgeEmployeeId: '0002'

