openapi: 3.0.0
info:
  version: 1.0.0
  title: Forgot Password API
  description: API documentation for user Forgot Password
tags:
  - name: Forgot Password
    description: User Forgot Password
paths:
  /forgot-password:
    post:
      summary: Forgot Password
      tags:
        - Forgot Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeId:
                  type: string
                email:
                  type: string
                newPassword:
                  type: string
              required:
                - employeeId
                - email
                - newPassword
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        '400':
          description: employeeId, email, and newPassword are required or newPassword is not match with confirmPassword
        '404':
          description: User not found
        '500':
          description: Internal server error
